[package]
name = "band_proc_macro"
version = "0.1.1"
edition = "2021"
description = "Support library for band"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.38"
quote = "1.0.33"

[lib]
proc-macro = true